import { ProductDoc, IngredientDoc } from "../types/catalog";

export const INITIAL_PRODUCTS: ProductDoc[] = [
  {
    id: "caramel-cold-brew",
    name: "Caramel Cold Brew",
    slug: "caramel-cold-brew",
    productType: "drink",
    category: "cold-coffee",
    categoryLabel: "Cold Coffee",
    description: "Slow-steeped cold brew layered with handcrafted caramel and velvet sweet cream.",
    basePrice: 180,
    currency: "INR",
    image: "/asset/caramel-cold-brew/frame-0001.webp",
    available: true,
    featured: true,
    tags: ["Signature", "Cold Brew", "Bestseller"],
    tasteNotes: ["Rich Caramel", "Dark Chocolate", "Silky Cream"],
    calories: 180,
    sweetnessProfile: 65,
    strengthProfile: 75,
    textureProfile: "Smooth & Velvety",
    temperatureProfile: "Iced",
    pairings: ["Almond Croissant", "Sea Salt Caramel Biscotti", "Dark Chocolate Truffle"],
    defaultConfiguration: {
      productId: "caramel-cold-brew",
      baseId: "cold-brew",
      milkId: "oat-milk",
      flavorId: "caramel",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: ["caramel-drizzle"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chocolate-frappe",
    name: "Chocolate Frappe",
    slug: "chocolate-frappe",
    productType: "drink",
    category: "frappe",
    categoryLabel: "Frappe",
    description: "Rich blended dark cocoa with velvety cream, fine ice crystals, and whipped top.",
    basePrice: 220,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Popular", "Decadent", "Blended"],
    tasteNotes: ["Deep Cacao", "Sweet Cream", "Smooth Ice"],
    calories: 340,
    sweetnessProfile: 80,
    strengthProfile: 50,
    textureProfile: "Thick & Frosted",
    temperatureProfile: "Blended",
    pairings: ["Belgian Waffle Bites", "Vanilla Bean Shortbread"],
    defaultConfiguration: {
      productId: "chocolate-frappe",
      baseId: "chocolate-base",
      milkId: "whole-milk",
      flavorId: "chocolate",
      sweetnessId: "sweetness-75",
      iceId: "regular-ice",
      toppingIds: ["whipped-cream", "chocolate-drizzle"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "strawberry-cream",
    name: "Strawberry Cream",
    slug: "strawberry-cream",
    productType: "drink",
    category: "creamy",
    categoryLabel: "Creamy",
    description: "Sweet strawberry puree swirled over chilled milk and soft vanilla foam.",
    basePrice: 210,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Refreshing", "Fruity", "Creamy"],
    tasteNotes: ["Ripe Berry", "Sweet Cream", "Crisp Milk"],
    calories: 210,
    sweetnessProfile: 70,
    strengthProfile: 20,
    textureProfile: "Silky Smooth",
    temperatureProfile: "Iced",
    pairings: ["New York Cheesecake Slice", "Pistachio Macaron"],
    defaultConfiguration: {
      productId: "strawberry-cream",
      baseId: "strawberry-base",
      milkId: "whole-milk",
      flavorId: "strawberry",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: ["strawberry-foam"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mango-smoothie",
    name: "Mango Smoothie",
    slug: "mango-smoothie",
    productType: "drink",
    category: "smoothie",
    categoryLabel: "Smoothie",
    description: "Sun-ripened tropical mango blended smooth with crushed ice and coconut undertones.",
    basePrice: 210,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Tropical", "Real Fruit", "Energizing"],
    tasteNotes: ["Golden Mango", "Tropical Sweet", "Citrus Spark"],
    calories: 220,
    sweetnessProfile: 75,
    strengthProfile: 15,
    textureProfile: "Thick Smoothie",
    temperatureProfile: "Blended",
    pairings: ["Coconut Chia Pudding", "Lemon Tart"],
    defaultConfiguration: {
      productId: "mango-smoothie",
      baseId: "mango-base",
      milkId: "almond-milk",
      flavorId: "mango",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "matcha-cloud",
    name: "Matcha Cloud",
    slug: "matcha-cloud",
    productType: "drink",
    category: "matcha",
    categoryLabel: "Matcha",
    description: "Pure stone-ground Japanese matcha layered under a cloud of cold oat foam.",
    basePrice: 230,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Zen", "Ceremonial", "Antioxidants"],
    tasteNotes: ["Earthy Matcha", "Subtle Sweet", "Velvet Oat"],
    calories: 160,
    sweetnessProfile: 45,
    strengthProfile: 70,
    textureProfile: "Light & Foamy",
    temperatureProfile: "Iced",
    pairings: ["Japanese Mochi Trio", "Matcha Financier"],
    defaultConfiguration: {
      productId: "matcha-cloud",
      baseId: "matcha",
      milkId: "oat-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-25",
      iceId: "light-ice",
      toppingIds: ["matcha-foam"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "vanilla-latte",
    name: "Vanilla Latte",
    slug: "vanilla-latte",
    productType: "drink",
    category: "hot-coffee",
    categoryLabel: "Hot Coffee",
    description: "Double espresso shot balanced with silky steamed milk and Madagascar vanilla bean syrup.",
    basePrice: 190,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Classic", "Comfort", "Espresso"],
    tasteNotes: ["Warm Vanilla", "Espresso Crema", "Sweet Milk"],
    calories: 200,
    sweetnessProfile: 55,
    strengthProfile: 80,
    textureProfile: "Warm & Silky",
    temperatureProfile: "Hot",
    pairings: ["Classic Butter Croissant", "Cinnamon Brioche Roll"],
    defaultConfiguration: {
      productId: "vanilla-latte",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-50",
      iceId: "no-ice",
      toppingIds: ["cocoa-dust"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mocha-cream",
    name: "Mocha Cream",
    slug: "mocha-cream",
    productType: "drink",
    category: "hot-coffee",
    categoryLabel: "Hot Coffee",
    description: "Bold espresso meets rich dark chocolate ganache, capped with thick whipped cream.",
    basePrice: 220,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Indulgent", "Chocolate & Coffee"],
    tasteNotes: ["Dark Mocha", "Roasted Nut", "Heavy Cream"],
    calories: 280,
    sweetnessProfile: 65,
    strengthProfile: 85,
    textureProfile: "Rich & Dense",
    temperatureProfile: "Hot",
    pairings: ["Hazelnut Babka", "Double Chocolate Cookie"],
    defaultConfiguration: {
      productId: "mocha-cream",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "chocolate",
      sweetnessId: "sweetness-50",
      iceId: "no-ice",
      toppingIds: ["whipped-cream", "cocoa-dust"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "berry-blast",
    name: "Berry Blast",
    slug: "berry-blast",
    productType: "drink",
    category: "smoothie",
    categoryLabel: "Smoothie",
    description: "Crisp chilled infusion of wild blackberry, raspberry, and crushed mint over ice.",
    basePrice: 180,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Zero Caffeine", "Wild Berries", "Crisp"],
    tasteNotes: ["Wild Berries", "Tart Brightness", "Cool Mint"],
    calories: 90,
    sweetnessProfile: 60,
    strengthProfile: 10,
    textureProfile: "Crisp & Light",
    temperatureProfile: "Iced",
    pairings: ["Granola Parfait", "Blueberry Scone"],
    defaultConfiguration: {
      productId: "berry-blast",
      baseId: "berry-base",
      milkId: "soy-milk",
      flavorId: "berry",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "espresso",
    name: "Espresso",
    slug: "espresso",
    productType: "drink",
    category: "hot-coffee",
    categoryLabel: "Hot Coffee",
    description: "Classic double shot of rich espresso roast featuring dense crema and deep cacao undertones.",
    basePrice: 120,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Bold", "Classic", "Pure Coffee"],
    tasteNotes: ["Dark Chocolate", "Toasted Walnut", "Golden Crema"],
    calories: 10,
    sweetnessProfile: 10,
    strengthProfile: 95,
    textureProfile: "Dense & Concentrated",
    temperatureProfile: "Hot",
    pairings: ["Almond Biscotti", "Butter Croissant"],
    defaultConfiguration: {
      productId: "espresso",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-0",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "small",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cappuccino",
    name: "Cappuccino",
    slug: "cappuccino",
    productType: "drink",
    category: "hot-coffee",
    categoryLabel: "Hot Coffee",
    description: "Harmonious balance of double espresso, velvety steamed milk, and a thick pillow of microfoam.",
    basePrice: 160,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Classic", "Velvety", "Balanced"],
    tasteNotes: ["Espresso Crema", "Sweet Milk Foam", "Dusting of Cocoa"],
    calories: 140,
    sweetnessProfile: 35,
    strengthProfile: 80,
    textureProfile: "Airy & Creamy",
    temperatureProfile: "Hot",
    pairings: ["Chocolate Croissant", "Cinnamon Roll"],
    defaultConfiguration: {
      productId: "cappuccino",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-25",
      iceId: "no-ice",
      toppingIds: ["cocoa-dust"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cafe-latte",
    name: "Café Latte",
    slug: "cafe-latte",
    productType: "drink",
    category: "hot-coffee",
    categoryLabel: "Hot Coffee",
    description: "Smooth espresso gently combined with steamed milk and a delicate top layer of latte art.",
    basePrice: 170,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Smooth", "Everyday Favorite"],
    tasteNotes: ["Roasted Caramel", "Gentle Espresso", "Warm Milk"],
    calories: 180,
    sweetnessProfile: 40,
    strengthProfile: 70,
    textureProfile: "Silky Smooth",
    temperatureProfile: "Hot",
    pairings: ["Butter Croissant", "Blueberry Muffin"],
    defaultConfiguration: {
      productId: "cafe-latte",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-25",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "iced-latte",
    name: "Iced Latte",
    slug: "iced-latte",
    productType: "drink",
    category: "cold-coffee",
    categoryLabel: "Cold Coffee",
    description: "Chilled milk poured over crystal ice and crowned with a fresh double shot of espresso.",
    basePrice: 180,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Chilled", "Refreshing Coffee", "Bestseller"],
    tasteNotes: ["Crisp Milk", "Bright Espresso", "Smooth Finish"],
    calories: 130,
    sweetnessProfile: 30,
    strengthProfile: 75,
    textureProfile: "Crisp & Refreshing",
    temperatureProfile: "Iced",
    pairings: ["Banana Walnut Loaf", "Grilled Cheese Toastie"],
    defaultConfiguration: {
      productId: "iced-latte",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-25",
      iceId: "regular-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cold-brew",
    name: "Classic Cold Brew",
    slug: "cold-brew",
    productType: "drink",
    category: "cold-coffee",
    categoryLabel: "Cold Coffee",
    description: "Pure single-origin coffee steeped in cold filtered water for 18 hours for maximum smoothness and low acidity.",
    basePrice: 160,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Single Origin", "Slow Steeped", "Low Acidity"],
    tasteNotes: ["Dark Cocoa", "Molasses", "Clean Finish"],
    calories: 15,
    sweetnessProfile: 15,
    strengthProfile: 85,
    textureProfile: "Light & Clean",
    temperatureProfile: "Iced",
    pairings: ["Almond Biscotti", "Avocado Toast"],
    defaultConfiguration: {
      productId: "cold-brew",
      baseId: "cold-brew",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-0",
      iceId: "regular-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "strawberry-refresher",
    name: "Strawberry Refresher",
    slug: "strawberry-refresher",
    productType: "drink",
    category: "smoothie",
    categoryLabel: "Refresher",
    description: "Crisp green coffee extract infused with real strawberry juice, hints of lime, and shaken over ice.",
    basePrice: 190,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Fruity", "Light Energy", "Shaken"],
    tasteNotes: ["Fresh Strawberry", "Lime Zest", "Subtle Energy"],
    calories: 110,
    sweetnessProfile: 65,
    strengthProfile: 25,
    textureProfile: "Crisp & Effervescent",
    temperatureProfile: "Iced",
    pairings: ["Blueberry Muffin", "Butter Croissant"],
    defaultConfiguration: {
      productId: "strawberry-refresher",
      baseId: "strawberry-base",
      milkId: "soy-milk",
      flavorId: "strawberry",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mango-passion-cooler",
    name: "Mango Passion Cooler",
    slug: "mango-passion-cooler",
    productType: "drink",
    category: "smoothie",
    categoryLabel: "Refresher",
    description: "Golden Alphonso mango pulp blended with tart passion fruit and shaken over ice for tropical ecstasy.",
    basePrice: 190,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Tropical", "Zero Caffeine", "Bright"],
    tasteNotes: ["Alphonso Mango", "Tangy Passion Fruit", "Citrus Splash"],
    calories: 130,
    sweetnessProfile: 75,
    strengthProfile: 10,
    textureProfile: "Thirst Quenching",
    temperatureProfile: "Iced",
    pairings: ["Coconut Chia Pudding", "Paneer Pesto Sandwich"],
    defaultConfiguration: {
      productId: "mango-passion-cooler",
      baseId: "mango-base",
      milkId: "soy-milk",
      flavorId: "mango",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "berry-citrus-cooler",
    name: "Berry Citrus Cooler",
    slug: "berry-citrus-cooler",
    productType: "drink",
    category: "smoothie",
    categoryLabel: "Refresher",
    description: "Wild blackberry and red raspberry infusion brightened with freshly squeezed lemon and mint sprigs.",
    basePrice: 180,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Antioxidants", "Zesty", "Iced"],
    tasteNotes: ["Wild Berries", "Lemon Spritz", "Garden Mint"],
    calories: 95,
    sweetnessProfile: 55,
    strengthProfile: 15,
    textureProfile: "Bright & Refreshing",
    temperatureProfile: "Iced",
    pairings: ["Blueberry Scone", "Avocado Toast"],
    defaultConfiguration: {
      productId: "berry-citrus-cooler",
      baseId: "berry-base",
      milkId: "soy-milk",
      flavorId: "berry",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "butter-croissant",
    name: "Butter Croissant",
    slug: "butter-croissant",
    productType: "bakery",
    category: "bakery",
    categoryLabel: "Bakery",
    description: "Flaky, golden, artisan all-butter French croissant with honeycomb crumb baked fresh every morning.",
    basePrice: 95,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Fresh Baked", "All Butter", "French Classic"],
    tasteNotes: ["Cultured Butter", "Golden Flake", "Warm Brioche"],
    calories: 260,
    sweetnessProfile: 20,
    strengthProfile: 0,
    textureProfile: "Flaky & Crispy",
    temperatureProfile: "Hot",
    pairings: ["Caramel Cold Brew", "Vanilla Latte", "Cappuccino"],
    defaultConfiguration: {
      productId: "butter-croissant",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-0",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chocolate-croissant",
    name: "Chocolate Croissant",
    slug: "chocolate-croissant",
    productType: "bakery",
    category: "bakery",
    categoryLabel: "Bakery",
    description: "Buttery laminated dough wrapped around two batons of semi-sweet Belgian dark chocolate.",
    basePrice: 110,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Belgian Chocolate", "Artisan Bakery"],
    tasteNotes: ["Semi-Sweet Chocolate", "Rich Butter", "Crisp Crust"],
    calories: 310,
    sweetnessProfile: 50,
    strengthProfile: 0,
    textureProfile: "Flaky & Melt-in-Mouth",
    temperatureProfile: "Hot",
    pairings: ["Classic Cold Brew", "Mocha Cream"],
    defaultConfiguration: {
      productId: "chocolate-croissant",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "chocolate",
      sweetnessId: "sweetness-25",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "blueberry-muffin",
    name: "Blueberry Muffin",
    slug: "blueberry-muffin",
    productType: "bakery",
    category: "bakery",
    categoryLabel: "Bakery",
    description: "Moist vanilla crumb bursting with wild blueberries, finished with crunchy demerara sugar crust.",
    basePrice: 90,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Wild Berries", "Breakfast Favorite"],
    tasteNotes: ["Juicy Blueberry", "Warm Vanilla", "Turbinado Sugar"],
    calories: 280,
    sweetnessProfile: 60,
    strengthProfile: 0,
    textureProfile: "Soft & Crumbly",
    temperatureProfile: "Hot",
    pairings: ["Vanilla Latte", "Iced Latte"],
    defaultConfiguration: {
      productId: "blueberry-muffin",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-50",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "banana-walnut-loaf",
    name: "Banana Walnut Loaf",
    slug: "banana-walnut-loaf",
    productType: "bakery",
    category: "bakery",
    categoryLabel: "Bakery",
    description: "Old-fashioned spiced banana bread studded with toasted California walnuts, served warm.",
    basePrice: 85,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Toasted Nuts", "Comfort Food"],
    tasteNotes: ["Ripe Banana", "Nutmeg", "Toasted Walnut"],
    calories: 290,
    sweetnessProfile: 55,
    strengthProfile: 0,
    textureProfile: "Dense & Moist",
    temperatureProfile: "Hot",
    pairings: ["Caramel Cold Brew", "Espresso"],
    defaultConfiguration: {
      productId: "banana-walnut-loaf",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-50",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chocolate-chip-cookie",
    name: "Chocolate Chip Cookie",
    slug: "chocolate-chip-cookie",
    productType: "bakery",
    category: "bakery",
    categoryLabel: "Bakery",
    description: "Thick, chewy brown-butter cookie loaded with melted dark chocolate chunks and sea salt flakes.",
    basePrice: 75,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Brown Butter", "Sea Salt", "Decadent"],
    tasteNotes: ["Melted Chocolate", "Caramelized Butter", "Sea Salt Flake"],
    calories: 250,
    sweetnessProfile: 70,
    strengthProfile: 0,
    textureProfile: "Chewy Center, Crisp Edge",
    temperatureProfile: "Hot",
    pairings: ["Cappuccino", "Classic Cold Brew"],
    defaultConfiguration: {
      productId: "chocolate-chip-cookie",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "chocolate",
      sweetnessId: "sweetness-75",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cinnamon-roll",
    name: "Cinnamon Roll",
    slug: "cinnamon-roll",
    productType: "bakery",
    category: "bakery",
    categoryLabel: "Bakery",
    description: "Warm brioche swirl filled with cinnamon sugar and topped with melted cream cheese icing.",
    basePrice: 120,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Warm Spice", "Iced", "Indulgence"],
    tasteNotes: ["Saigon Cinnamon", "Cream Cheese Glaze", "Fluffy Dough"],
    calories: 380,
    sweetnessProfile: 85,
    strengthProfile: 0,
    textureProfile: "Soft & Gooey",
    temperatureProfile: "Hot",
    pairings: ["Espresso", "Classic Cold Brew"],
    defaultConfiguration: {
      productId: "cinnamon-roll",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-75",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "grilled-cheese-toastie",
    name: "Grilled Cheese Toastie",
    slug: "grilled-cheese-toastie",
    productType: "snack",
    category: "savory",
    categoryLabel: "Savory Bites",
    description: "Artisan sourdough toastie oozing with sharp aged cheddar, mozzarella, and herb garlic butter.",
    basePrice: 140,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Warm Savory", "Melted Cheese", "Comfort"],
    tasteNotes: ["Aged Cheddar", "Garlic Herb Butter", "Toasted Sourdough"],
    calories: 390,
    sweetnessProfile: 5,
    strengthProfile: 0,
    textureProfile: "Crispy & Gooey",
    temperatureProfile: "Hot",
    pairings: ["Iced Latte", "Classic Cold Brew"],
    defaultConfiguration: {
      productId: "grilled-cheese-toastie",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-0",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "avocado-toast",
    name: "Avocado Sourdough Toast",
    slug: "avocado-toast",
    productType: "snack",
    category: "savory",
    categoryLabel: "Savory Bites",
    description: "Smashed Hass avocado on toasted multigrain sourdough topped with chili flakes, lemon zest, and toasted seeds.",
    basePrice: 175,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Plant Based", "Superfood", "Healthy"],
    tasteNotes: ["Creamy Avocado", "Chili Kick", "Toasted Sesame & Pumpkin Seed"],
    calories: 260,
    sweetnessProfile: 5,
    strengthProfile: 0,
    textureProfile: "Crunchy & Creamy",
    temperatureProfile: "Hot",
    pairings: ["Matcha Cloud", "Classic Cold Brew"],
    defaultConfiguration: {
      productId: "avocado-toast",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-0",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "paneer-pesto-sandwich",
    name: "Paneer Pesto Sandwich",
    slug: "paneer-pesto-sandwich",
    productType: "snack",
    category: "savory",
    categoryLabel: "Savory Bites",
    description: "Herb-marinated cottage cheese slabs layered with house basil pesto, sun-dried tomatoes, and crisp rocket in focaccia.",
    basePrice: 165,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Gourmet", "High Protein", "Herbaceous"],
    tasteNotes: ["Basil Pesto", "Fresh Cottage Cheese", "Sun-Dried Tomato"],
    calories: 370,
    sweetnessProfile: 10,
    strengthProfile: 0,
    textureProfile: "Hearty & Tender",
    temperatureProfile: "Hot",
    pairings: ["Iced Latte", "Mango Smoothie"],
    defaultConfiguration: {
      productId: "paneer-pesto-sandwich",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-0",
      iceId: "no-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_INGREDIENTS: IngredientDoc[] = [
  // BASES
  {
    id: "cold-brew",
    name: "Cold Brew",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 80, sweetnessScore: 10, richnessScore: 70 },
  },
  {
    id: "espresso",
    name: "Espresso",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 95, sweetnessScore: 5, richnessScore: 85 },
  },
  {
    id: "matcha",
    name: "Matcha",
    type: "base",
    priceDelta: 20,
    available: true,
    metadata: { strengthScore: 65, sweetnessScore: 15, richnessScore: 60 },
  },
  {
    id: "strawberry-base",
    name: "Strawberry Base",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 15, sweetnessScore: 70, richnessScore: 30 },
  },
  {
    id: "mango-base",
    name: "Mango Base",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 10, sweetnessScore: 75, richnessScore: 40 },
  },
  {
    id: "berry-base",
    name: "Berry Base",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 15, sweetnessScore: 60, richnessScore: 35 },
  },
  {
    id: "chocolate-base",
    name: "Chocolate Base",
    type: "base",
    priceDelta: 10,
    available: true,
    metadata: { strengthScore: 50, sweetnessScore: 70, richnessScore: 85 },
  },
  {
    id: "vanilla-base",
    name: "Vanilla Base",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 20, sweetnessScore: 60, richnessScore: 50 },
  },

  // MILKS
  {
    id: "whole-milk",
    name: "Whole Milk",
    type: "milk",
    priceDelta: 0,
    available: true,
    metadata: { creaminessScore: 75, richnessScore: 70 },
  },
  {
    id: "oat-milk",
    name: "Oat Milk",
    type: "milk",
    priceDelta: 30,
    available: true,
    metadata: { creaminessScore: 85, richnessScore: 65 },
  },
  {
    id: "almond-milk",
    name: "Almond Milk",
    type: "milk",
    priceDelta: 30,
    available: true,
    metadata: { creaminessScore: 60, richnessScore: 50 },
  },
  {
    id: "soy-milk",
    name: "Soy Milk",
    type: "milk",
    priceDelta: 20,
    available: true,
    metadata: { creaminessScore: 70, richnessScore: 60 },
  },

  // FLAVORS
  {
    id: "caramel",
    name: "Caramel",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 30, richnessScore: 25 },
  },
  {
    id: "vanilla",
    name: "Vanilla",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 25, richnessScore: 20 },
  },
  {
    id: "chocolate",
    name: "Chocolate",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 25, richnessScore: 35 },
  },
  {
    id: "hazelnut",
    name: "Hazelnut",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 20, richnessScore: 30 },
  },
  {
    id: "strawberry",
    name: "Strawberry",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 35, richnessScore: 15 },
  },
  {
    id: "mango",
    name: "Mango",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 35, richnessScore: 20 },
  },
  {
    id: "berry",
    name: "Berry",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 30, richnessScore: 15 },
  },
  {
    id: "flavor-none",
    name: "No Flavor Syrup",
    type: "flavor",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 0, richnessScore: 0 },
  },

  // SWEETNESS
  {
    id: "sweetness-0",
    name: "0% Unsweetened",
    type: "sweetness",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 0 },
  },
  {
    id: "sweetness-25",
    name: "25% Light Sweetness",
    type: "sweetness",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 25 },
  },
  {
    id: "sweetness-50",
    name: "50% Balanced Sweetness",
    type: "sweetness",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 50 },
  },
  {
    id: "sweetness-75",
    name: "75% Extra Sweetness",
    type: "sweetness",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 75 },
  },
  {
    id: "sweetness-100",
    name: "100% Full Sweetness",
    type: "sweetness",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 100 },
  },

  // ICE
  {
    id: "no-ice",
    name: "No Ice",
    type: "ice",
    priceDelta: 0,
    available: true,
    metadata: { chillScore: 20 },
  },
  {
    id: "light-ice",
    name: "Light Ice",
    type: "ice",
    priceDelta: 0,
    available: true,
    metadata: { chillScore: 50 },
  },
  {
    id: "regular-ice",
    name: "Regular Ice",
    type: "ice",
    priceDelta: 0,
    available: true,
    metadata: { chillScore: 80 },
  },
  {
    id: "extra-ice",
    name: "Extra Ice",
    type: "ice",
    priceDelta: 0,
    available: true,
    metadata: { chillScore: 100 },
  },

  // TOPPINGS
  {
    id: "whipped-cream",
    name: "Whipped Cream",
    type: "topping",
    priceDelta: 30,
    available: true,
    metadata: { creaminessScore: 25, richnessScore: 20 },
  },
  {
    id: "caramel-drizzle",
    name: "Caramel Drizzle",
    type: "topping",
    priceDelta: 20,
    available: true,
    metadata: { sweetnessScore: 15, richnessScore: 15 },
  },
  {
    id: "chocolate-drizzle",
    name: "Chocolate Drizzle",
    type: "topping",
    priceDelta: 20,
    available: true,
    metadata: { sweetnessScore: 15, richnessScore: 20 },
  },
  {
    id: "cocoa-dust",
    name: "Cocoa Dust",
    type: "topping",
    priceDelta: 15,
    available: true,
    metadata: { strengthScore: 10, richnessScore: 15 },
  },
  {
    id: "strawberry-foam",
    name: "Strawberry Cold Foam",
    type: "topping",
    priceDelta: 35,
    available: true,
    metadata: { creaminessScore: 20, sweetnessScore: 20 },
  },
  {
    id: "matcha-foam",
    name: "Matcha Cold Foam",
    type: "topping",
    priceDelta: 35,
    available: true,
    metadata: { creaminessScore: 20, strengthScore: 15 },
  },

  // SIZES
  {
    id: "small",
    name: "Small (250ml)",
    type: "size",
    priceDelta: -20,
    available: true,
    metadata: { volumeMl: 250 },
  },
  {
    id: "medium",
    name: "Medium (350ml)",
    type: "size",
    priceDelta: 0,
    available: true,
    metadata: { volumeMl: 350 },
  },
  {
    id: "large",
    name: "Large (450ml)",
    type: "size",
    priceDelta: 40,
    available: true,
    metadata: { volumeMl: 450 },
  },
];
