import { ProductDoc, IngredientDoc } from "../types/catalog";

export const INITIAL_PRODUCTS: ProductDoc[] = [
  {
    id: "caramel-cold-brew",
    name: "Caramel Cold Brew",
    slug: "caramel-cold-brew",
    category: "cold-coffee",
    categoryLabel: "Cold Coffee",
    description: "Slow-steeped cold brew layered with handcrafted caramel and velvet sweet cream.",
    basePrice: 180,
    currency: "INR",
    image: "/asset/caramel-cold-brew/frame_0001.webp",
    available: true,
    featured: true,
    tags: ["Signature", "Cold Brew", "Bestseller"],
    tasteNotes: ["Rich Caramel", "Dark Chocolate", "Silky Cream"],
    calories: 180,
    sweetnessProfile: 65,
    strengthProfile: 75,
    textureProfile: "Smooth & Velvety",
    temperatureProfile: "Iced",
    defaultConfiguration: {
      productId: "caramel-cold-brew",
      baseId: "cold-brew",
      milkId: "oat-milk",
      flavorId: "caramel",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: ["caramel-drizzle"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chocolate-frappe",
    name: "Chocolate Frappe",
    slug: "chocolate-frappe",
    category: "frappe",
    categoryLabel: "Frappe",
    description: "Rich blended dark cocoa with velvety cream, fine ice crystals, and whipped top.",
    basePrice: 220,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Popular", "Decadent", "Blended"],
    tasteNotes: ["Deep Cacao", "Sweet Cream", "Smooth Ice"],
    calories: 340,
    sweetnessProfile: 80,
    strengthProfile: 50,
    textureProfile: "Thick & Frosted",
    temperatureProfile: "Blended",
    defaultConfiguration: {
      productId: "chocolate-frappe",
      baseId: "chocolate-base",
      milkId: "whole-milk",
      flavorId: "chocolate",
      sweetnessId: "sweetness-75",
      iceId: "regular-ice",
      toppingIds: ["whipped-cream", "chocolate-drizzle"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "strawberry-cream",
    name: "Strawberry Cream",
    slug: "strawberry-cream",
    category: "creamy",
    categoryLabel: "Creamy",
    description: "Sweet strawberry puree swirled over chilled milk and soft vanilla foam.",
    basePrice: 210,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Refreshing", "Fruity", "Creamy"],
    tasteNotes: ["Ripe Berry", "Sweet Cream", "Crisp Milk"],
    calories: 210,
    sweetnessProfile: 70,
    strengthProfile: 20,
    textureProfile: "Silky Smooth",
    temperatureProfile: "Iced",
    defaultConfiguration: {
      productId: "strawberry-cream",
      baseId: "strawberry-base",
      milkId: "whole-milk",
      flavorId: "strawberry",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: ["strawberry-foam"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mango-smoothie",
    name: "Mango Smoothie",
    slug: "mango-smoothie",
    category: "smoothie",
    categoryLabel: "Smoothie",
    description: "Sun-ripened tropical mango blended smooth with crushed ice and coconut undertones.",
    basePrice: 210,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Tropical", "Real Fruit", "Energizing"],
    tasteNotes: ["Golden Mango", "Tropical Sweet", "Citrus Spark"],
    calories: 220,
    sweetnessProfile: 75,
    strengthProfile: 15,
    textureProfile: "Thick Smoothie",
    temperatureProfile: "Blended",
    defaultConfiguration: {
      productId: "mango-smoothie",
      baseId: "mango-base",
      milkId: "almond-milk",
      flavorId: "mango",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "matcha-cloud",
    name: "Matcha Cloud",
    slug: "matcha-cloud",
    category: "matcha",
    categoryLabel: "Matcha",
    description: "Pure stone-ground Japanese matcha layered under a cloud of cold oat foam.",
    basePrice: 230,
    currency: "INR",
    image: "",
    available: true,
    featured: true,
    tags: ["Zen", "Ceremonial", "Antioxidants"],
    tasteNotes: ["Earthy Matcha", "Subtle Sweet", "Velvet Oat"],
    calories: 160,
    sweetnessProfile: 45,
    strengthProfile: 70,
    textureProfile: "Light & Foamy",
    temperatureProfile: "Iced",
    defaultConfiguration: {
      productId: "matcha-cloud",
      baseId: "matcha",
      milkId: "oat-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-25",
      iceId: "light-ice",
      toppingIds: ["matcha-foam"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "vanilla-latte",
    name: "Vanilla Latte",
    slug: "vanilla-latte",
    category: "hot-coffee",
    categoryLabel: "Hot Coffee",
    description: "Double espresso shot balanced with silky steamed milk and Madagascar vanilla bean syrup.",
    basePrice: 190,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Classic", "Comfort", "Espresso"],
    tasteNotes: ["Warm Vanilla", "Espresso Crema", "Sweet Milk"],
    calories: 200,
    sweetnessProfile: 55,
    strengthProfile: 80,
    textureProfile: "Warm & Silky",
    temperatureProfile: "Hot",
    defaultConfiguration: {
      productId: "vanilla-latte",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "vanilla",
      sweetnessId: "sweetness-50",
      iceId: "no-ice",
      toppingIds: ["cocoa-dust"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mocha-cream",
    name: "Mocha Cream",
    slug: "mocha-cream",
    category: "hot-coffee",
    categoryLabel: "Hot Coffee",
    description: "Bold espresso meets rich dark chocolate ganache, capped with thick whipped cream.",
    basePrice: 220,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Indulgent", "Chocolate & Coffee"],
    tasteNotes: ["Dark Mocha", "Roasted Nut", "Heavy Cream"],
    calories: 280,
    sweetnessProfile: 65,
    strengthProfile: 85,
    textureProfile: "Rich & Dense",
    temperatureProfile: "Hot",
    defaultConfiguration: {
      productId: "mocha-cream",
      baseId: "espresso",
      milkId: "whole-milk",
      flavorId: "chocolate",
      sweetnessId: "sweetness-50",
      iceId: "no-ice",
      toppingIds: ["whipped-cream", "cocoa-dust"],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "berry-blast",
    name: "Berry Blast",
    slug: "berry-blast",
    category: "smoothie",
    categoryLabel: "Smoothie",
    description: "Crisp chilled infusion of wild blackberry, raspberry, and crushed mint over ice.",
    basePrice: 180,
    currency: "INR",
    image: "",
    available: true,
    featured: false,
    tags: ["Zero Caffeine", "Wild Berries", "Crisp"],
    tasteNotes: ["Wild Berries", "Tart Brightness", "Cool Mint"],
    calories: 90,
    sweetnessProfile: 60,
    strengthProfile: 10,
    textureProfile: "Crisp & Light",
    temperatureProfile: "Iced",
    defaultConfiguration: {
      productId: "berry-blast",
      baseId: "berry-base",
      milkId: "soy-milk",
      flavorId: "berry",
      sweetnessId: "sweetness-50",
      iceId: "regular-ice",
      toppingIds: [],
      sizeId: "medium",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_INGREDIENTS: IngredientDoc[] = [
  // BASES
  {
    id: "cold-brew",
    name: "Cold Brew",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 80, sweetnessScore: 10, richnessScore: 70 },
  },
  {
    id: "espresso",
    name: "Espresso",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 95, sweetnessScore: 5, richnessScore: 85 },
  },
  {
    id: "matcha",
    name: "Matcha",
    type: "base",
    priceDelta: 20,
    available: true,
    metadata: { strengthScore: 65, sweetnessScore: 15, richnessScore: 60 },
  },
  {
    id: "strawberry-base",
    name: "Strawberry Base",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 15, sweetnessScore: 70, richnessScore: 30 },
  },
  {
    id: "mango-base",
    name: "Mango Base",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 10, sweetnessScore: 75, richnessScore: 40 },
  },
  {
    id: "berry-base",
    name: "Berry Base",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 15, sweetnessScore: 60, richnessScore: 35 },
  },
  {
    id: "chocolate-base",
    name: "Chocolate Base",
    type: "base",
    priceDelta: 10,
    available: true,
    metadata: { strengthScore: 50, sweetnessScore: 70, richnessScore: 85 },
  },
  {
    id: "vanilla-base",
    name: "Vanilla Base",
    type: "base",
    priceDelta: 0,
    available: true,
    metadata: { strengthScore: 20, sweetnessScore: 60, richnessScore: 50 },
  },

  // MILKS
  {
    id: "whole-milk",
    name: "Whole Milk",
    type: "milk",
    priceDelta: 0,
    available: true,
    metadata: { creaminessScore: 75, richnessScore: 70 },
  },
  {
    id: "oat-milk",
    name: "Oat Milk",
    type: "milk",
    priceDelta: 30,
    available: true,
    metadata: { creaminessScore: 85, richnessScore: 65 },
  },
  {
    id: "almond-milk",
    name: "Almond Milk",
    type: "milk",
    priceDelta: 30,
    available: true,
    metadata: { creaminessScore: 60, richnessScore: 50 },
  },
  {
    id: "soy-milk",
    name: "Soy Milk",
    type: "milk",
    priceDelta: 20,
    available: true,
    metadata: { creaminessScore: 70, richnessScore: 60 },
  },

  // FLAVORS
  {
    id: "caramel",
    name: "Caramel",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 30, richnessScore: 25 },
  },
  {
    id: "vanilla",
    name: "Vanilla",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 25, richnessScore: 20 },
  },
  {
    id: "chocolate",
    name: "Chocolate",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 25, richnessScore: 35 },
  },
  {
    id: "hazelnut",
    name: "Hazelnut",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 20, richnessScore: 30 },
  },
  {
    id: "strawberry",
    name: "Strawberry",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 35, richnessScore: 15 },
  },
  {
    id: "mango",
    name: "Mango",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 35, richnessScore: 20 },
  },
  {
    id: "berry",
    name: "Berry",
    type: "flavor",
    priceDelta: 25,
    available: true,
    metadata: { sweetnessScore: 30, richnessScore: 15 },
  },
  {
    id: "flavor-none",
    name: "No Flavor Syrup",
    type: "flavor",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 0, richnessScore: 0 },
  },

  // SWEETNESS
  {
    id: "sweetness-0",
    name: "0% Unsweetened",
    type: "sweetness",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 0 },
  },
  {
    id: "sweetness-25",
    name: "25% Light Sweetness",
    type: "sweetness",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 25 },
  },
  {
    id: "sweetness-50",
    name: "50% Balanced Sweetness",
    type: "sweetness",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 50 },
  },
  {
    id: "sweetness-75",
    name: "75% Extra Sweetness",
    type: "sweetness",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 75 },
  },
  {
    id: "sweetness-100",
    name: "100% Full Sweetness",
    type: "sweetness",
    priceDelta: 0,
    available: true,
    metadata: { sweetnessScore: 100 },
  },

  // ICE
  {
    id: "no-ice",
    name: "No Ice",
    type: "ice",
    priceDelta: 0,
    available: true,
    metadata: { chillScore: 20 },
  },
  {
    id: "light-ice",
    name: "Light Ice",
    type: "ice",
    priceDelta: 0,
    available: true,
    metadata: { chillScore: 50 },
  },
  {
    id: "regular-ice",
    name: "Regular Ice",
    type: "ice",
    priceDelta: 0,
    available: true,
    metadata: { chillScore: 80 },
  },
  {
    id: "extra-ice",
    name: "Extra Ice",
    type: "ice",
    priceDelta: 0,
    available: true,
    metadata: { chillScore: 100 },
  },

  // TOPPINGS
  {
    id: "whipped-cream",
    name: "Whipped Cream",
    type: "topping",
    priceDelta: 30,
    available: true,
    metadata: { creaminessScore: 25, richnessScore: 20 },
  },
  {
    id: "caramel-drizzle",
    name: "Caramel Drizzle",
    type: "topping",
    priceDelta: 20,
    available: true,
    metadata: { sweetnessScore: 15, richnessScore: 15 },
  },
  {
    id: "chocolate-drizzle",
    name: "Chocolate Drizzle",
    type: "topping",
    priceDelta: 20,
    available: true,
    metadata: { sweetnessScore: 15, richnessScore: 20 },
  },
  {
    id: "cocoa-dust",
    name: "Cocoa Dust",
    type: "topping",
    priceDelta: 15,
    available: true,
    metadata: { strengthScore: 10, richnessScore: 15 },
  },
  {
    id: "strawberry-foam",
    name: "Strawberry Cold Foam",
    type: "topping",
    priceDelta: 35,
    available: true,
    metadata: { creaminessScore: 20, sweetnessScore: 20 },
  },
  {
    id: "matcha-foam",
    name: "Matcha Cold Foam",
    type: "topping",
    priceDelta: 35,
    available: true,
    metadata: { creaminessScore: 20, strengthScore: 15 },
  },

  // SIZES
  {
    id: "small",
    name: "Small (250ml)",
    type: "size",
    priceDelta: -20,
    available: true,
    metadata: { volumeMl: 250 },
  },
  {
    id: "medium",
    name: "Medium (350ml)",
    type: "size",
    priceDelta: 0,
    available: true,
    metadata: { volumeMl: 350 },
  },
  {
    id: "large",
    name: "Large (450ml)",
    type: "size",
    priceDelta: 40,
    available: true,
    metadata: { volumeMl: 450 },
  },
];
