import { DrinkItem, NavItem } from "@/types";

export const BRAND = {
  name: "AI CAFÉ",
  tagline: "Your Drink. Your Way.",
  supporting: "Crafted by AI. Inspired by You.",
  soundtrackTitle: "AI Café — Morning Vibes",
  phrases: {
    coldBrew: "Cold Brew. Smoothly crafted.",
    makeItYours: "Make it yours.",
    personalized: "Personalized by AI.",
  },
};

export const NAV_ITEMS: NavItem[] = [
  { label: "Home", href: "/#hero" },
  { label: "Menu", href: "/#menu" },
  { label: "AI Barista", href: "/barista", badge: "AI" },
  { label: "Build Your Drink", href: "/builder" },
  { label: "Our Story", href: "/#story" },
];

export const APPROVED_DRINKS: DrinkItem[] = [
  {
    id: "caramel-cold-brew",
    name: "Caramel Cold Brew",
    category: "cold-brew",
    categoryLabel: "Signature Cold Brew",
    description: "Slow-steeped cold brew layered with handcrafted caramel and velvet sweet cream.",
    price: 180,
    popular: true,
    tag: "Signature",
    temperature: "Iced",
    calories: 180,
    tasteNotes: ["Rich Caramel", "Dark Chocolate", "Silky Cream"],
  },
  {
    id: "chocolate-frappe",
    name: "Chocolate Frappe",
    category: "frappe",
    categoryLabel: "Blended Specialty",
    description: "Rich blended dark cocoa with velvety cream, ice crystals, and whipped top.",
    price: 220,
    popular: true,
    tag: "Popular",
    temperature: "Blended",
    calories: 340,
    tasteNotes: ["Deep Cacao", "Sweet Cream", "Smooth Ice"],
  },
  {
    id: "strawberry-cream",
    name: "Strawberry Cream",
    category: "smoothie",
    categoryLabel: "Fruit & Cream",
    description: "Sweet strawberry puree swirled over chilled milk and soft vanilla foam.",
    price: 210,
    tag: "Refreshing",
    temperature: "Iced",
    calories: 210,
    tasteNotes: ["Ripe Berry", "Sweet Cream", "Crisp Milk"],
  },
  {
    id: "mango-smoothie",
    name: "Mango Smoothie",
    category: "smoothie",
    categoryLabel: "Fruit & Cream",
    description: "Sun-ripened tropical mango blended smooth with crushed ice and coconut undertones.",
    price: 210,
    temperature: "Blended",
    calories: 220,
    tasteNotes: ["Golden Mango", "Tropical Sweet", "Citrus Spark"],
  },
  {
    id: "matcha-cloud",
    name: "Matcha Cloud",
    category: "tea",
    categoryLabel: "Botanical & Tea",
    description: "Pure stone-ground Japanese matcha layered under a cloud of cold oat foam.",
    price: 230,
    popular: true,
    tag: "Zen",
    temperature: "Iced",
    calories: 160,
    tasteNotes: ["Earthy Matcha", "Subtle Sweet", "Velvet Oat"],
  },
  {
    id: "vanilla-latte",
    name: "Vanilla Latte",
    category: "espresso",
    categoryLabel: "Espresso Classic",
    description: "Double espresso shot balanced with silky steamed milk and Madagascar vanilla bean syrup.",
    price: 190,
    temperature: "Hot",
    calories: 200,
    tasteNotes: ["Warm Vanilla", "Espresso Crema", "Sweet Milk"],
  },
  {
    id: "mocha-cream",
    name: "Mocha Cream",
    category: "espresso",
    categoryLabel: "Espresso Classic",
    description: "Bold espresso meets rich dark chocolate ganache, capped with thick whipped cream.",
    price: 220,
    temperature: "Hot",
    calories: 280,
    tasteNotes: ["Dark Mocha", "Roasted Nut", "Heavy Cream"],
  },
  {
    id: "berry-blast",
    name: "Berry Blast",
    category: "tea",
    categoryLabel: "Fruit & Refresh",
    description: "Crisp chilled infusion of wild blackberry, raspberry, and crushed mint over ice.",
    price: 180,
    tag: "Zero Caffeine",
    temperature: "Iced",
    calories: 90,
    tasteNotes: ["Wild Berries", "Tart Brightness", "Cool Mint"],
  },
];

export const TOTAL_HERO_FRAMES = 192;
export const HERO_FRAME_PATH = "/asset/caramel-cold-brew/frame-";
