import { DrinkItem, NavItem } from "@/types";

export const BRAND = {
  name: "AI CAFÉ",
  tagline: "Your Drink. Your Way.",
  supporting: "Crafted by AI. Inspired by You.",
  soundtrackTitle: "AI Café — Morning Vibes",
  phrases: {
    coldBrew: "Cold Brew. Smoothly crafted.",
    makeItYours: "Make it yours.",
    personalized: "Personalized by AI.",
  },
};

export const NAV_ITEMS: NavItem[] = [
  { label: "Home", href: "/" },
  { label: "Menu", href: "/menu" },
  { label: "AI Barista", href: "/barista", badge: "AI" },
  { label: "Build Your Drink", href: "/builder" },
  { label: "Our Story", href: "/#story" },
];

export const APPROVED_DRINKS: DrinkItem[] = [
  {
    id: "caramel-cold-brew",
    name: "Caramel Cold Brew",
    category: "cold-brew",
    categoryLabel: "Signature Cold Brew",
    description: "Slow-steeped cold brew layered with handcrafted caramel and velvet sweet cream.",
    price: 180,
    popular: true,
    tag: "Signature",
    temperature: "Iced",
    calories: 180,
    tasteNotes: ["Rich Caramel", "Dark Chocolate", "Silky Cream"],
  },
  {
    id: "chocolate-frappe",
    name: "Chocolate Frappe",
    category: "frappe",
    categoryLabel: "Blended Specialty",
    description: "Rich blended dark cocoa with velvety cream, ice crystals, and whipped top.",
    price: 220,
    popular: true,
    tag: "Popular",
    temperature: "Blended",
    calories: 340,
    tasteNotes: ["Deep Cacao", "Sweet Cream", "Smooth Ice"],
  },
  {
    id: "strawberry-cream",
    name: "Strawberry Cream",
    category: "smoothie",
    categoryLabel: "Fruit & Cream",
    description: "Sweet strawberry puree swirled over chilled milk and soft vanilla foam.",
    price: 210,
    tag: "Refreshing",
    temperature: "Iced",
    calories: 210,
    tasteNotes: ["Ripe Berry", "Sweet Cream", "Crisp Milk"],
  },
  {
    id: "mango-smoothie",
    name: "Mango Smoothie",
    category: "smoothie",
    categoryLabel: "Fruit & Cream",
    description: "Sun-ripened tropical mango blended smooth with crushed ice and coconut undertones.",
    price: 210,
    temperature: "Blended",
    calories: 220,
    tasteNotes: ["Golden Mango", "Tropical Sweet", "Citrus Spark"],
  },
  {
    id: "matcha-cloud",
    name: "Matcha Cloud",
    category: "tea",
    categoryLabel: "Botanical & Tea",
    description: "Pure stone-ground Japanese matcha layered under a cloud of cold oat foam.",
    price: 230,
    popular: true,
    tag: "Zen",
    temperature: "Iced",
    calories: 160,
    tasteNotes: ["Earthy Matcha", "Subtle Sweet", "Velvet Oat"],
  },
  {
    id: "vanilla-latte",
    name: "Vanilla Latte",
    category: "espresso",
    categoryLabel: "Espresso Classic",
    description: "Double espresso shot balanced with silky steamed milk and Madagascar vanilla bean syrup.",
    price: 190,
    temperature: "Hot",
    calories: 200,
    tasteNotes: ["Warm Vanilla", "Espresso Crema", "Sweet Milk"],
  },
  {
    id: "mocha-cream",
    name: "Mocha Cream",
    category: "espresso",
    categoryLabel: "Espresso Classic",
    description: "Bold espresso meets rich dark chocolate ganache, capped with thick whipped cream.",
    price: 220,
    temperature: "Hot",
    calories: 280,
    tasteNotes: ["Dark Mocha", "Roasted Nut", "Heavy Cream"],
  },
  {
    id: "berry-blast",
    name: "Berry Blast",
    category: "tea",
    categoryLabel: "Fruit & Refresh",
    description: "Crisp chilled infusion of wild blackberry, raspberry, and crushed mint over ice.",
    price: 180,
    tag: "Zero Caffeine",
    temperature: "Iced",
    calories: 90,
    tasteNotes: ["Wild Berries", "Tart Brightness", "Cool Mint"],
  },
  {
    id: "espresso",
    name: "Espresso",
    category: "espresso",
    categoryLabel: "Espresso Classic",
    description: "Classic double shot of rich espresso roast featuring dense crema and deep cacao undertones.",
    price: 120,
    tag: "Bold",
    temperature: "Hot",
    calories: 10,
    tasteNotes: ["Dark Chocolate", "Toasted Walnut", "Golden Crema"],
    pairings: ["Almond Biscotti", "Butter Croissant"],
  },
  {
    id: "cappuccino",
    name: "Cappuccino",
    category: "espresso",
    categoryLabel: "Espresso Classic",
    description: "Harmonious balance of double espresso, velvety steamed milk, and a thick pillow of microfoam.",
    price: 160,
    popular: true,
    tag: "Classic",
    temperature: "Hot",
    calories: 140,
    tasteNotes: ["Espresso Crema", "Sweet Milk Foam", "Dusting of Cocoa"],
    pairings: ["Chocolate Croissant", "Cinnamon Roll"],
  },
  {
    id: "cafe-latte",
    name: "Café Latte",
    category: "espresso",
    categoryLabel: "Espresso Classic",
    description: "Smooth espresso gently combined with steamed milk and a delicate top layer of latte art.",
    price: 170,
    temperature: "Hot",
    calories: 180,
    tasteNotes: ["Roasted Caramel", "Gentle Espresso", "Warm Milk"],
    pairings: ["Butter Croissant", "Blueberry Muffin"],
  },
  {
    id: "iced-latte",
    name: "Iced Latte",
    category: "cold-brew",
    categoryLabel: "Chilled Coffee",
    description: "Chilled milk poured over crystal ice and crowned with a fresh double shot of espresso.",
    price: 180,
    popular: true,
    tag: "Bestseller",
    temperature: "Iced",
    calories: 130,
    tasteNotes: ["Crisp Milk", "Bright Espresso", "Smooth Finish"],
    pairings: ["Banana Walnut Loaf", "Grilled Cheese Toastie"],
  },
  {
    id: "cold-brew",
    name: "Classic Cold Brew",
    category: "cold-brew",
    categoryLabel: "Slow Steeped",
    description: "Pure single-origin coffee steeped in cold filtered water for 18 hours for maximum smoothness.",
    price: 160,
    temperature: "Iced",
    calories: 15,
    tasteNotes: ["Dark Cocoa", "Molasses", "Clean Finish"],
    pairings: ["Almond Biscotti", "Avocado Toast"],
  },
  {
    id: "strawberry-refresher",
    name: "Strawberry Refresher",
    category: "smoothie",
    categoryLabel: "Fruit Refresher",
    description: "Crisp green coffee extract infused with real strawberry juice, hints of lime, and shaken over ice.",
    price: 190,
    popular: true,
    tag: "Light Energy",
    temperature: "Iced",
    calories: 110,
    tasteNotes: ["Fresh Strawberry", "Lime Zest", "Subtle Energy"],
    pairings: ["Blueberry Muffin", "Butter Croissant"],
  },
  {
    id: "mango-passion-cooler",
    name: "Mango Passion Cooler",
    category: "smoothie",
    categoryLabel: "Tropical Cooler",
    description: "Golden Alphonso mango pulp blended with tart passion fruit and shaken over ice for tropical ecstasy.",
    price: 190,
    temperature: "Iced",
    calories: 130,
    tasteNotes: ["Alphonso Mango", "Tangy Passion Fruit", "Citrus Splash"],
    pairings: ["Coconut Chia Pudding", "Paneer Pesto Sandwich"],
  },
  {
    id: "berry-citrus-cooler",
    name: "Berry Citrus Cooler",
    category: "smoothie",
    categoryLabel: "Fruit Refresher",
    description: "Wild blackberry and red raspberry infusion brightened with freshly squeezed lemon and mint sprigs.",
    price: 180,
    temperature: "Iced",
    calories: 95,
    tasteNotes: ["Wild Berries", "Lemon Spritz", "Garden Mint"],
    pairings: ["Blueberry Scone", "Avocado Toast"],
  },
  {
    id: "butter-croissant",
    name: "Butter Croissant",
    category: "bakery",
    categoryLabel: "Artisan Bakery",
    description: "Flaky, golden, artisan all-butter French croissant with honeycomb crumb baked fresh daily.",
    price: 95,
    popular: true,
    tag: "Fresh Baked",
    temperature: "Hot",
    calories: 260,
    tasteNotes: ["Cultured Butter", "Golden Flake", "Warm Brioche"],
    pairings: ["Caramel Cold Brew", "Vanilla Latte", "Cappuccino"],
    productType: "bakery",
  },
  {
    id: "chocolate-croissant",
    name: "Chocolate Croissant",
    category: "bakery",
    categoryLabel: "Artisan Bakery",
    description: "Buttery laminated dough wrapped around two batons of semi-sweet Belgian dark chocolate.",
    price: 110,
    popular: true,
    tag: "Belgian Chocolate",
    temperature: "Hot",
    calories: 310,
    tasteNotes: ["Semi-Sweet Chocolate", "Rich Butter", "Crisp Crust"],
    pairings: ["Classic Cold Brew", "Mocha Cream"],
    productType: "bakery",
  },
  {
    id: "blueberry-muffin",
    name: "Blueberry Muffin",
    category: "bakery",
    categoryLabel: "Artisan Bakery",
    description: "Moist vanilla crumb bursting with wild blueberries, finished with crunchy demerara sugar crust.",
    price: 90,
    temperature: "Hot",
    calories: 280,
    tasteNotes: ["Juicy Blueberry", "Warm Vanilla", "Turbinado Sugar"],
    pairings: ["Vanilla Latte", "Iced Latte"],
    productType: "bakery",
  },
  {
    id: "banana-walnut-loaf",
    name: "Banana Walnut Loaf",
    category: "bakery",
    categoryLabel: "Artisan Bakery",
    description: "Old-fashioned spiced banana bread studded with toasted California walnuts, served warm.",
    price: 85,
    temperature: "Hot",
    calories: 290,
    tasteNotes: ["Ripe Banana", "Nutmeg", "Toasted Walnut"],
    pairings: ["Caramel Cold Brew", "Espresso"],
    productType: "bakery",
  },
  {
    id: "chocolate-chip-cookie",
    name: "Chocolate Chip Cookie",
    category: "bakery",
    categoryLabel: "Artisan Bakery",
    description: "Thick, chewy brown-butter cookie loaded with melted dark chocolate chunks and sea salt flakes.",
    price: 75,
    temperature: "Hot",
    calories: 250,
    tasteNotes: ["Melted Chocolate", "Caramelized Butter", "Sea Salt Flake"],
    pairings: ["Cappuccino", "Classic Cold Brew"],
    productType: "bakery",
  },
  {
    id: "cinnamon-roll",
    name: "Cinnamon Roll",
    category: "bakery",
    categoryLabel: "Artisan Bakery",
    description: "Warm brioche swirl filled with cinnamon sugar and topped with melted cream cheese icing.",
    price: 120,
    popular: true,
    tag: "Warm Spice",
    temperature: "Hot",
    calories: 380,
    tasteNotes: ["Saigon Cinnamon", "Cream Cheese Glaze", "Fluffy Dough"],
    pairings: ["Espresso", "Classic Cold Brew"],
    productType: "bakery",
  },
  {
    id: "grilled-cheese-toastie",
    name: "Grilled Cheese Toastie",
    category: "savory",
    categoryLabel: "Savory Bites",
    description: "Artisan sourdough toastie oozing with sharp aged cheddar, mozzarella, and herb garlic butter.",
    price: 140,
    popular: true,
    tag: "Melted Cheese",
    temperature: "Hot",
    calories: 390,
    tasteNotes: ["Aged Cheddar", "Garlic Herb Butter", "Toasted Sourdough"],
    pairings: ["Iced Latte", "Classic Cold Brew"],
    productType: "snack",
  },
  {
    id: "avocado-toast",
    name: "Avocado Sourdough Toast",
    category: "savory",
    categoryLabel: "Savory Bites",
    description: "Smashed Hass avocado on toasted multigrain sourdough topped with chili flakes, lemon zest, and seeds.",
    price: 175,
    tag: "Healthy",
    temperature: "Hot",
    calories: 260,
    tasteNotes: ["Creamy Avocado", "Chili Kick", "Toasted Seeds"],
    pairings: ["Matcha Cloud", "Classic Cold Brew"],
    productType: "snack",
  },
  {
    id: "paneer-pesto-sandwich",
    name: "Paneer Pesto Sandwich",
    category: "savory",
    categoryLabel: "Savory Bites",
    description: "Herb-marinated cottage cheese slabs layered with house basil pesto and sun-dried tomatoes in focaccia.",
    price: 165,
    popular: true,
    tag: "High Protein",
    temperature: "Hot",
    calories: 370,
    tasteNotes: ["Basil Pesto", "Fresh Cottage Cheese", "Sun-Dried Tomato"],
    pairings: ["Iced Latte", "Mango Smoothie"],
    productType: "snack",
  },
];

export const TOTAL_HERO_FRAMES = 192;
export const HERO_FRAME_PATH = "/asset/caramel-cold-brew/frame-";
