import React from "react";
import type { Metadata } from "next";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { Container } from "@/components/layout/container";
import { FileText, CheckCircle2, AlertTriangle, ShieldCheck } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions governing AI CAFÉ orders, customizations, and AI concierge guidance.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-cream text-espresso">
      <Navbar />

      <section className="pt-32 pb-20 sm:pt-40 sm:pb-28">
        <Container>
          <div className="max-w-3xl mx-auto">
            {/* Header */}
            <div className="mb-12">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-caramel/15 text-espresso text-xs font-semibold uppercase tracking-wider mb-4">
                <FileText className="w-3.5 h-3.5 text-caramel" />
                <span>Service Agreement</span>
              </div>
              <h1 className="font-serif text-4xl sm:text-5xl font-bold text-espresso tracking-tight mb-4">
                Terms of Service
              </h1>
              <p className="text-sm text-warmgray font-mono">
                Effective Date: September 2026 • AI CAFÉ Production V7.3
              </p>
            </div>

            <div className="prose prose-stone max-w-none space-y-10 text-espresso/80 leading-relaxed font-sans text-sm sm:text-base">
              {/* Section 1 */}
              <div>
                <h2 className="font-serif text-2xl font-bold text-espresso mb-3 flex items-center gap-2">
                  <CheckCircle2 className="w-5 h-5 text-caramel" />
                  1. Agreement to Terms
                </h2>
                <p>
                  Welcome to <strong>AI CAFÉ</strong>. By accessing our platform, consulting our AI Barista Concierge, or utilizing our interactive Drink Builder Studio, you agree to comply with and be bound by these Terms of Service.
                </p>
              </div>

              {/* Section 2 */}
              <div>
                <h2 className="font-serif text-2xl font-bold text-espresso mb-3 flex items-center gap-2">
                  <ShieldCheck className="w-5 h-5 text-caramel" />
                  2. Server-Authoritative Pricing & Catalog
                </h2>
                <p>
                  All beverage pricing displayed on AI CAFÉ is denominated in Indian Rupees (INR, ₹). Pricing calculations for base drinks, modifiers (milk substitutes, artisanal syrups, sizes, foams, and toppings) are authoritative and determined strictly by our server-side catalog engine.
                </p>
                <p className="mt-2">
                  In the event of any discrepancy between client-rendered previews and server validation, server-validated pricing shall govern.
                </p>
              </div>

              {/* Section 3 */}
              <div>
                <h2 className="font-serif text-2xl font-bold text-espresso mb-3 flex items-center gap-2">
                  <FileText className="w-5 h-5 text-caramel" />
                  3. Drink Builder Customization & Formulation
                </h2>
                <p>
                  Our Drink Builder allows customers to create custom beverage DNA formulations. Formulations must adhere to operational safety limits (e.g. valid ingredient combinations, maximum topping volumes, and allergen constraints). We reserve the right to decline or calibrate formulations that exceed physical preparation tolerances.
                </p>
              </div>

              {/* Section 4 */}
              <div>
                <h2 className="font-serif text-2xl font-bold text-espresso mb-3 flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5 text-caramel" />
                  4. AI Barista Concierge & Dietary Advice
                </h2>
                <p>
                  Recommendations and sensory descriptions generated by the AI Barista Concierge are provided for informational and culinary guidance purposes only.
                </p>
                <p className="mt-2">
                  While our system grounds recommendations in actual catalog metadata, customers with severe medical allergies (such as dairy, nut, or gluten sensitivities) should exercise standard personal caution. The AI Concierge does not make medical, physiological, or health claims.
                </p>
              </div>

              {/* Section 5 */}
              <div>
                <h2 className="font-serif text-2xl font-bold text-espresso mb-3">
                  5. Accounts & Governance
                </h2>
                <p>
                  Customers are responsible for maintaining the confidentiality of their authentication credentials. Privileged roles (Staff, Administrator, Super Administrator) are managed under strict hierarchical governance. Any unauthorized attempt to tamper with roles, bypass API access controls, or manipulate prices will result in immediate account termination.
                </p>
              </div>

              {/* Section 6 */}
              <div>
                <h2 className="font-serif text-2xl font-bold text-espresso mb-3">
                  6. Phase 8 Notice: Upcoming Commerce & Fulfillment
                </h2>
                <p>
                  Phase 7.3 establishes production readiness, security, and catalog validation. Final payment processing, checkout fulfillment, and kitchen ticketing will be introduced in Phase 8 under verified payment gateway compliance. No live financial charges are processed during Phase 7.x previews.
                </p>
              </div>
            </div>
          </div>
        </Container>
      </section>

      <Footer />
    </main>
  );
}
